version: '3'

services:
  redis-proxy-cache-service-0:
    build:
      context: ./RedisProxy
      args:
        PROXY_PORT: 5000
    environment:
      - REDIS_ADDRESS=redis-service
      - CACHE_EXP_SECS=5
      - CACHE_MAX_KEYS=3
    ports:
      - 5000:5000
  redis-proxy-cache-service-1:
    build:
      context: ./RedisProxy
      args:
        PROXY_PORT: 5001
    environment:
      - REDIS_ADDRESS=redis-service
      - CACHE_EXP_SECS=5
      - CACHE_MAX_KEYS=3
    ports:
      - 5001:5001
  redis-service:
    image: redis:latest
  test-service:
    build:
      context: ./RedisProxyTest
