version: '3'

services:
  redis-service:
    image: redis:latest
    logging:
      driver: 'none'
    ports:
      - 6379:6379
  redis-proxy-cache-service-0:
    build:
      context: ./RedisProxy
      args:
        PROXY_PORT_: 5000
    environment:
      - MAX_CONNECTIONS=4
      - REDIS_ADDRESS=redis-service
      - CACHE_EXP_SECS=2
      - CACHE_MAX_KEYS=3
    ports:
      - 5000:5000
    depends_on:
      - 'redis-service'
    logging:
      driver: 'none'
  redis-proxy-cache-service-1:
    build:
      context: ./RedisProxy
      args:
        PROXY_PORT_: 5001
    environment:
      - MAX_CONNECTIONS=4
      - REDIS_ADDRESS=redis-service
      - CACHE_EXP_SECS=2
      - CACHE_MAX_KEYS=3
    ports:
      - 5001:5001
    depends_on:
      - 'redis-service'
    logging:
      driver: 'none'
  test-service:
    build:
      context: ./RedisProxyTest
    environment:
      - REDIS_ADDRESS=redis-service
      - PROXY_ADDRESS_0=redis-proxy-cache-service-0
      - PROXY_ADDRESS_1=redis-proxy-cache-service-1
      - PROXY_PORT_0=5000
      - PROXY_PORT_1=5001
    depends_on:
      - 'redis-proxy-cache-service-0'
      - 'redis-proxy-cache-service-1'
      - 'redis-service'
